export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const TOKEN_LOADED = 'TOKEN_LOADED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const PROFILE_SIGNUP_FAIL = 'PROFILE_SIGNUP_FAIL';
export const DELETE_PROFILE = 'DELETE_PROFILE'